/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int result;
	/*
	 * insert server code here
	 */
	printf("Calculando add...\n");
	printf("x=%d\n", argp->x);
	printf("y=%d\n", argp->y);
	result = argp->x + argp->y;
	return &result;
}

int *sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	printf("Calculando sub...\n");
	result = argp->x - argp->y;

	return &result;
}